Tum: derleme calistirma


derleme:
	g++ -I ./include/ -o ./lib/Stack.o -c ./src/Stack.cpp
	g++ -I ./include/ -o ./lib/StackDugum.o -c ./src/StackDugum.cpp
	g++ -I ./include/ -o ./lib/Avl.o -c ./src/Avl.cpp
	g++ -I ./include/ -o ./lib/AvlDugum.o -c ./src/AvlDugum.cpp
	g++ -I ./include/ -o ./bin/main.exe ./lib/Stack.o ./lib/StackDugum.o ./lib/Avl.o ./lib/AvlDugum.o ./src/main.cpp
	
calistirma:
	./bin/main.exe